config/routes.rb
ParasquidCs2001::Application.routes.draw do
  root to: "welcome#index"

  get "querying" => 'querying#index'

  get "uploads" => 'uploads#index'
  namespace :uploads do
    post "challenge_categories"
    post "challlenges"
    post "challenge_participants"
    get "generate_prediction_data"
  end

  match '/query' => Prediction, anchor: false
end

app/models/active_model/model.rb
module ActiveModel
  module Model
    def self.included(base)
      base.class_eval do
        extend  ActiveModel::Naming
        extend  ActiveModel::Translation
        include ActiveModel::Validations
        include ActiveModel::Conversion
      end
    end

    def initialize(params={})
      params.each do |attr, value|
        self.public_send("#{attr}=", value)
      end if params
    end

    def persisted?
      false
    end
  end
end

app/models/prediction_data.rb
class PredictionData
	include Mongoid::Document

	field :categories, type: Array, default: []
	field :submitters, type: Array, default: []
	field :total_prize, type: Integer, default: 0
	field :top_prize, type: Integer, default: 0
	field :challenge_length, type: Integer, default: 0
	field :passing_submissions, type: Float, default: 0.0

	def self.import_challenge_categories(data)
		column_name = :challenge_categories
		DB.drop_table?(column_name)
		DB.create_table(column_name) do
			String "Category__r.Name"
			String "Challenge__r.Challenge_Id__c"
		end
		insert_into_database(data, column_name)
	end

	def self.import_challenges(data)
		column_name = :challenges
		DB.drop_table?(column_name)
		DB.create_table(column_name) do
			String "Challenge_Id__c"
			Integer "Length_of_Contest__c"
			String "Top_Prize__c" # this field has dollar signs :(
			Integer "Total_Prize_Money__c"
		end
		insert_into_database(data, column_name)
	end

	def self.import_challenge_participants(data)
		column_name = :challenge_participants
		DB.drop_table?(column_name)
		DB.create_table(column_name) do
			String "Member__r.Name"
			String "Challenge__r.Challenge_Id__c"
			Float "Score__c" # a score of more than 75.00 is a valid submission
		end
		insert_into_database(data, column_name)
	end

	def self.generate
		# generate the prediction data lines
		# categories.join(' '), submitters.join(' '), total_prize, top_prize, challenge_length, passing_submissions
		lines = {}

		# reduce the challenge categories into lines and arrays by creating a hash
		# {:challenge_id => [category1, category2, category3]}
		DB[:challenge_categories].each do |row|
			lines[row[:"Challenge__r.Challenge_Id__c"]] ||= {}
			lines[row[:"Challenge__r.Challenge_Id__c"]][:categories] ||= []
			lines[row[:"Challenge__r.Challenge_Id__c"]][:categories].push(row[:"Category__r.Name"])
		end

		# include the challenge info
		DB[:challenges].each do |row|
			lines[row[:"Challenge_Id__c"]] ||= {}
			lines[row[:"Challenge_Id__c"]][:challenge_length] = row[:"Length_of_Contest__c"]
			lines[row[:"Challenge_Id__c"]][:top_prize] = row[:"Top_Prize__c"].to_s.gsub('$','').gsub(',','').to_i
			lines[row[:"Challenge_Id__c"]][:total_prize] = row[:"Total_Prize_Money__c"]
			puts lines[row[:"Challenge_Id__c"]][:top_prize]
		end

		# include the submitters
		DB[:challenge_participants].each do |row|
			lines[row[:"Challenge__r.Challenge_Id__c"]] ||= {}
			lines[row[:"Challenge__r.Challenge_Id__c"]][:submitters] ||= []
			lines[row[:"Challenge__r.Challenge_Id__c"]][:submitters].push(row[:"Member__r.Name"]) if row[:"Score__c"] > 0
			passing_submissions = lines[row[:"Challenge__r.Challenge_Id__c"]][:passing_submissions] ||= 0
			lines[row[:"Challenge__r.Challenge_Id__c"]][:passing_submissions] = passing_submissions + 1 if row[:"Score__c"] > 75
		end

		# create the database
		lines.each do |line|
			PredictionData.create line.last
		end

		# clear in-memory database
	end

  def self.to_csv(options={})
    CSV.generate(options) do |csv|
      self.all.each do |elem|
				csv << [elem.passing_submissions,
					"#{elem.categories.sort.join(' ')}",
					"#{elem.submitters.sort.join(' ')}",
					elem.total_prize,
					elem.top_prize,
					elem.challenge_length
				]
      end
    end
  end

	private

	def self.sanitize(data, column_names)
    data.each do |row|
			row.delete_if {|key, value| !column_names.include? key.to_sym}
		end
	end

	def self.insert_into_database(data, column_name)
		data = sanitize(data, DB[column_name].columns)
		data.each do |row|
			begin
				DB[column_name.to_sym].insert row
			rescue Exception => e
				Rails.logger.error e.inspect # log exceptions but continue anyway
			end
		end
	end
end

app/models/upload.rb
class Upload
	include ActiveModel::Model

	attr_accessor :data
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/querying_controller.rb
class QueryingController < ApplicationController
  def index
  end
end

app/controllers/uploads_controller.rb
require 'csv'
class UploadsController < ApplicationController
	def index
		@upload = Upload.new
		@challenge_participants = (DB[:challenge_participants] if DB.table_exists?(:challenge_participants)) || []
		@challenges = (DB[:challenges] if DB.table_exists?(:challenges))  || []
		@challenge_categories = (DB[:challenge_categories] if DB.table_exists?(:challenge_categories))  || []
	end

  def challenge_categories
		data = CSV.new params[:upload][:data].tempfile
  	PredictionData.import_challenge_categories(data.to_hash)
  	redirect_to uploads_path
  end

  def challlenges
		data = CSV.new params[:upload][:data].tempfile
  	PredictionData.import_challenges(data.to_hash)
  	redirect_to uploads_path
  end

  def challenge_participants
		data = CSV.new params[:upload][:data].tempfile
  	PredictionData.import_challenge_participants(data.to_hash)
  	redirect_to uploads_path, notice: 'Upload completed'
  end

  def generate_prediction_data
    # drop it like it's hot
    # PredictionData.delete_all
    PredictionData.generate
  	send_data PredictionData.to_csv, filename: 'prediction_data.csv'
  end
end

class CSV
	def to_hash
		headers = self.shift.map {|i| i.to_s }
		string_data = self.map {|row| row.map {|cell| cell.to_s } }
		array_of_hashes = string_data.map {|row| Hash[*headers.zip(row).flatten] }
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/querying_helper.rb
module QueryingHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ParasquidCs2001</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<div class="row">
<div class="span12">
	<%= yield %>
</div>
</div>
</div>
</body>
</html>

app/views/querying/index.html.erb
<h1>Querying#index</h1>
<p>Find me in app/views/querying/index.html.erb</p>

app/views/uploads/index.html.erb
<div class="well well-small">
	<%= simple_form_for(@upload, url: uploads_challenge_participants_path, :html => {:class => 'form-horizontal' }) do |f| %>
		<%= f.input :data, :as => :file, label: 'challenge-participants-export.csv' %>
	<div class="control-group">
    <div class="controls">
      <button type="submit" class="btn btn-danger">Create Upload</button> <%= @challenge_participants.count %> records
    </div>
  </div>
	<% end %>
</div>

<div class="well well-small">
	<%= simple_form_for(@upload, url: uploads_challlenges_path, :html => {:class => 'form-horizontal' }) do |f| %>
		<%= f.input :data, :as => :file, label: 'challenge-export.csv' %>
		<div class="control-group">
	    <div class="controls">
	      <button type="submit" class="btn btn-warning">Create Upload</button> <%= @challenges.count %> records
	    </div>
	  </div>
	<% end %>
</div>

<div class="well well-small">
	<%= simple_form_for(@upload, url: uploads_challenge_categories_path, :html => {:class => 'form-horizontal' }) do |f| %>
		<%= f.input :data, :as => :file, label: 'challenge-categories-export.csv' %>
		<div class="control-group">
	    <div class="controls">
	      <button type="submit" class="btn btn-success">Create Upload</button> <%= @challenge_categories.count %> records
	    </div>
	  </div>
	<% end %>
</div>

<%= link_to "Back", root_path, :class => 'btn btn-primary' %>

app/views/welcome/index.html.erb
<h1>Welcome to the Cloudspokes Google Prediction API Challenge</h1>
<h2>You need to perform these steps</h2>
<ol>
	<li><%= link_to "Upload", uploads_path %> the data exports</li>
	<li><%= link_to "Download", uploads_generate_prediction_data_path %> the prediction data</li>
	<li><%= link_to "Import", "https://storage.cloud.google.com/", target: '_blank' %> the prediction data into Google Cloud Storage</li>
	<li><%= link_to "Query", query_path %> the prediction api</li>
</ol>